name: GH Page Deploy

# only on master push
on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    # set up node version
    - name: Read .nvmrc
      run: NVMRC=$(cat .nvmrc)

    - name: Use Node.js (.nvmrc)
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: lts/*
        
    # install dependencies
    - name: Install and Build
      run: |
        npm install
        npm run generate-pdf
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        CLEAN: true